version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: unleash-db
    environment:
      POSTGRES_PASSWORD: some_password
      POSTGRES_USER: unleash_user
      POSTGRES_DB: unleash
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash_user -d unleash"]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: unleash
      DATABASE_USERNAME: unleash_user
      DATABASE_PASSWORD: some_password
      DATABASE_SSL: "false"
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    name: unleash-network
